export default {
  WEBHOOK_VERIFY_TOKEN: process.env.WEBHOOK_VERIFY_TOKEN,
  GRAPH_API_TOKEN: process.env.GRAPH_API_TOKEN,
  PORT: process.env.PORT || 3000,
  BUSINESS_PHONE: process.env.BUSINESS_PHONE,
  API_VERSION: process.env.API_VERSION || 'v21.0',
  SPREADSHEET_ID: process.env.SPREADSHEET_ID,
  CHATGPT_API_KEY: process.env.CHATGPT_API_KEY,
}